### ISSUE TITLE
测试数据集未找到(dataset not found in http://www.cvlibs.net/datasets/.kitti/eval_odometry.php)

### ISSUE THREAD

**Issue by zikun007** [datawhalechina/smoothly-vslam#1]
大佬你好,我在学习这个项目后,最后需要测试结果时,没有在http://www.cvlibs.net/datasets/.kitti/eval_odometry.php找到kitti数据集

然后我在kitti官网上下载了一个data_object_image_2数据集,但是项目代码不能正常工作

请问这个项目的测试数据集还可以怎么获取?

**Comment by hu-minghao** [comment]
一.数据
KITTI数据集：
链接:https://pan.baidu.com/s/1Kr3qoS4pwVsYn03XnxPU8A 
提取码:3p92
(参考: https://blog.csdn.net/qq_36814762/article/details/136634482)
ch12中demo测试需要的是其中：data_odometry_gray 数据集
数据集结构：data_odometry_gray/dataset/sequences/xx

二.运行
编译工程后
修改配置文件：ch12/myslam/config/default.yaml
![image](https://github.com/user-attachments/assets/03d9d151-4c06-4e57-8fab-8a1eb4e0b899)
将路径替换为本地数据路径
运行命令：
./run_kitti_stereo -config_file=path/to/ch12/myslam/config/default.yaml

**Comment by zikun007** [comment]
@hu-minghao 感谢大佬，这个demo可以跑了！
